@startuml Jissyu2_1
actor ユーザー as user
boundary ブラウザ as B
control  web.php as web
control Jissyu3_1Controller as jissyu
boundary input.blade.php as input
boundary output.blade.php as output

user -> B : 該当ページをリクエスト[/Jissyu2]
B -> web : GET[/Jissyu3]
web -> jissyu : @index
jissyu -> input
user -> input :送信ボタンを押下
input -> web :POST
web -> jissyu : @post
jissyu -> output


@enduml